# Generated by Django 2.0.6 on 2018-09-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180903_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='content_type',
            field=models.ForeignKey(default='<function now at 0x7fa8d270fbf8>', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
