# Generated by Django 2.0.6 on 2018-09-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180903_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='iscompany',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='main_division',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='paper1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='paper2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='refer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='relation_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='sub_division',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
