# Generated by Django 2.0.6 on 2018-06-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Vulner',
        ),
    ]

    atomic = False
