# Generated by Django 2.0.6 on 2018-06-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180614_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulner',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vulner',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
