# Generated by Django 2.0.6 on 2018-06-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180615_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulner',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
