# Generated by Django 2.0.6 on 2018-06-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180615_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulner',
            name='severity',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
