# Generated by Django 2.0.6 on 2018-06-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_vulner_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulner',
            name='severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
